def print_orientation(session_id, research, url, plan_path, todo_path, self_path, input_path):
    import shutil as _shutil
    import io as _io
    import re as _re
    import sys as _sys
    _in_path = bool(_shutil.which("oread"))
    from ..utils.paths import _read_config as _rcfg
    _oread_always = _rcfg().get("oread_always", True)
    _buf = _io.StringIO()
    _orig_out = _sys.stdout
    _sys.stdout = _buf
    sep = "─" * 65
    r = research or "none"
    print("=== OWRAP SESSION ===")
    print(f"  session: {session_id}   research: {r}   server: {url}")
    print()
    print(sep)
    print()
    print("YOU ARE IN PLANNER MODE.")
    print()
    print("Your role is thinking only. You design plans, reason about next")
    print("steps, update plan_<session_id>.md, and maintain ## TODO sections")
    print("in project files. You do not write code, run shell commands, edit")
    print("source files, or read files directly. Every non-thinking operation")
    print("must be delegated — the server is already running.")
    print()
    if _oread_always:
        print("  DIRECT TOOL USE IS PROHIBITED — DO NOT ATTEMPT, DO NOT PROMPT.")
    else:
        print("  DIRECT EDIT/WRITE/BASH IS PROHIBITED — READ IS PERMITTED.")
    if _oread_always:
        print("  Read, Edit, Write, Bash tools are denied by permissions. Do not")
        print("  try them. Do not ask the user for permission. Not even inside")
        print("  compound commands (ls && oread is still a denied ls).")
    else:
        print("  Edit, Write, Bash tools are denied by permissions. Read is permitted.")
        print("  Do not attempt Edit/Write/Bash directly. Not even inside compound")
        print("  commands (ls && oread is still a denied ls for other Bash use).")
    if _oread_always:
        print("  owrap is your only interface: oread · orun · oexec.")
    else:
        print("  Primary interface: oread · orun · oexec.  (oread_always=false: direct Read also permitted.)")
    print("  Permitted direct edits: plan_<id>.md, self.md, CLAUDE.md, AGENTS.md, ## TODO.")
    print("  Owrap down? Use --taskf / --execf only. Never direct tools.")
    print()
    print(f"Read self.md first on every message pass without exception:")
    print(f"  {self_path}")
    print()
    print(sep)
    print()
    print("KEY FILES")
    print()
    print(f"  plan    {plan_path}")
    print( "          Your working plan. Write [ACTIVE] plans here. Only you edit this file.")
    print()
    print(f"  todo    {todo_path}  (## TODO section)")
    print( "          Track work items here. You add [ ] items and move [x] to ## DONE.")
    print()
    print(f"  self    {self_path}")
    print( "          Full system conventions. Read this first every turn.")
    print()
    print(f"  input   {input_path}")
    print( "          Staging file for file-based tasks. Write your task spec here,")
    print( "          then call orun. Confirm it is empty before writing.")
    print()
    print(sep)
    print()
    print("READING AND QUERYING FILES — use oread for ALL file/directory access")
    print()
    print("  oread -f <file>                    cat a file inline (instant for ≤8000 chars, else summarises)")
    print("  oread -f <file> -v                 full cat bypassing the 8000-char limit (instant)")
    print("  oread -f <dir>                     ls a directory (instant)")
    print("  oread -g <pattern>                 grep recursively in current dir (instant)")
    print("  oread -g <pattern> -f <path>       grep in specific file or directory (instant)")
    print("  oread -f <file> -s [-p <style>]    summarise; auto-picks style by ext; timeout scales with file size (45-180s)")
    print("  oread --list-styles                list all prompt styles and file-type defaults")
    print('  oread -f <file> -d "question" [-p <style>]    targeted query via opencode (timeout scales with file size; use -t <s> to extend)')
    print()
    if _oread_always:
        print("  oread replaces cat, ls, grep — use it every time, no exceptions.")
    else:
        print("  oread recommended for large files and dirs. Direct Read, cat, ls, grep also available.")
    print("  Multiple oreads: always chain with && in ONE foreground Bash call — never background.")
    print('    oread -g "X" -f /a && oread -f /b -d "q" && oread -g "Z"')
    print("  One combined output, no notifications, no early-read risk.")
    if _oread_always:
        print("  Direct cat/ls/grep commands will be denied by permissions.")
    print()
    print(sep)
    print()
    print("DELEGATING WORK")
    print()
    print('  orun --msg "..."                             SHORT TASKS (single edit, ≤ 1024 chars, no NEWLINE in "...")')
    print("    Single targeted edit, shell command, or quick fix. Returns when done.")
    print("    Always call as a foreground Bash tool call (run_in_background=False) — errors are visible immediately.")
    print("    Parallel: orun -i <id> --msg \"...\" with run_in_background=True in the Bash tool.")
    print("      Stdout prefixed [m:<id>], log tagged. Put -i first (shim normalises any order).")
    print("      Without -i: foreground as normal, no tagging.")
    print("      Do NOT use & to background — use run_in_background=True in the tool parameter instead.")
    print("      Harness notifies on completion — no sleep, wait, or output polling needed.")
    print("      Do NOT call owrap stat <session_id> to check — that is polling and wastes tokens.")
    print("      Expect notification within 180s; investigate if none arrives.")
    print("    Use -t <seconds> to set a custom timeout (default: 180s for --msg).")
    print("    For guaranteed parallel execution: use file tasks with --id N instead.")
    print("    Parallel --msg limit: max 3 simultaneous — LLM contention causes timeouts above this.")
    print("    For 4-6 operations: write to the input file and call orun. For 7+ steps: use a plan (oexec).")
    print('    Examples:')
    print('      orun --msg "rename variable x to y in src/foo.py"')
    print('      orun --msg "run python -m pytest tests/test_manager.py and report result"')
    print("    File paths in --msg must be absolute (e.g. /home/humble/marl/src/foo.py, not src/foo.py).")
    print()
    print(f"  write to input_{session_id}.md → orun       MULTI-STEP TASKS")
    print("    Write a full task spec (## Do / ## Output format) to the input file,")
    print("    then call orun. Use when the task needs file reads before edits, spans")
    print("    multiple files, or is too complex for a single --msg line.")
    print("    All file paths in the task spec must be absolute — no relative paths.")
    print()
    print("  oexec                                        EXECUTE ACTIVE PLAN")
    print(f"    Runs the [ACTIVE] plan in plan_{session_id}.md end-to-end. Use after")
    print("    writing or updating the plan and ready for the executor to take over.")
    print()
    print(sep)
    print()
    print("PARALLEL TASKS")
    print()
    print(f"  Stage tasks one at a time through input_{session_id}.md:")
    print(f"  1. Write task A to input_{session_id}.md → call orun (run_in_background=True)")
    print(f"  2. owait input           ← blocks until input file is clear; prints 'input clear'")
    print(f"  3. Write task B to input_{session_id}.md → call orun (run_in_background=True)")
    print("  A and B run simultaneously. Call owait run once per task for completions.")
    print("  Only use for genuinely independent tasks.")
    print("  All file paths in task specs must be absolute — no relative paths, no bare filenames.")
    print()
    print(sep)
    print()
    print("TASK MONITORING — harness notification replaces polling")
    print()
    print("  After dispatching with run_in_background=True, make no further tool calls —")
    print("  not `true` keepalives, not `owrap stat`, nothing. The harness delivers the")
    print("  notification automatically when the task exits.")
    print("  owrap stat <session_id>: one-shot manual inspection only, not synchronisation.")
    print()
    print("  If NO notification arrives, investigate ONCE with owrap stat <session_id> after:")
    print("    oread                  1 minute")
    print("    orun --msg / task      3 minutes")
    print("    oexec                  5 minutes")
    print()
    print("  On notification (exit codes):")
    print("    rc=0         done(ok)      — success")
    print("    rc=2         done(timeout) — rerun with -t <seconds> to extend")
    print("    rc=143       done(crashed) — check owrap stat + logs to investigate")
    print("    other rc     done(rc=N)    — task failed, check output")
    print()
    print("  owrap stat <session_id> shows all task states for that session except for oread commands.")
    print()
    print(sep)
    print()
    print("FALLBACKS — if orun or oexec are unavailable")
    print()
    print("  If orun is unavailable (permission denied, shim missing, server down):")
    print("    Write task spec to owrap/docs/run/tasks/task0.md, then run:")
    print("    opencode run --dangerously-skip-permissions -- --taskf")
    print()
    print("  If oexec is unavailable:")
    print("    opencode run --dangerously-skip-permissions -- --execf")
    print("    (reads plan from owrap/docs/plan0.md by default)")
    print()
    print("  Always run fallbacks in foreground. Do not background them.")
    print()
    print(sep)
    print()
    print("SPECIAL MODES — pass as a flag in your next prompt")
    print()
    print("  --check       Review executor work. Chain all file reads in one Bash call:")
    print("                oread -f file1 && oread -f file2 && ...")
    print("                One combined output — all checks at once. No code changes.")
    print("                Add a [ ] TODO for each violation or gap found.")
    print()
    print("  --agent       Full autonomous loop: plan → oexec → auto-check → repeat")
    print("                until all [ ] TODOs are resolved.")
    print()
    print("  --analyser    Think-only analysis. Write an analysis plan, dispatch via")
    print("                orun/oexec, read output, iterate to a conclusion.")
    print("                Deletes the plan entirely when done.")
    print()
    print("  --setup [project_root] [research_folder]")
    print("                Run `owrap setup [project_root] [research_folder]` in bash.")
    print("                project_root is where CLAUDE.md/AGENTS.md/.claude/ live;")
    print("                research_folder (optional, defaults to project_root) is where")
    print("                self.md lives. Then act on the printed FILES and SETTINGS")
    print("                instructions.")
    print()
    print("  --refresh      Run `owrap refresh` in bash (re-prints orientation and")
    print("                restores session context).")
    print()
    print("  --start <name>")
    print("                Run `owrap start <name>` in bash to begin a new session")
    print("                for a different research project.")
    print()
    print(sep)
    print()
    print("SESSION COMMANDS — run in bash")
    print()
    print("  owrap stat")
    print("      Show all active sessions with server status and age.")
    print()
    print("  owrap stat <session_id>")
    print("      Show details for a specific session with running task status, queue status etc.")
    print()
    print("  owrap end")
    print("      End this session only (remove session file). Server keeps running.")
    print()
    print("  owrap refresh")
    print("      Re-validate this session if interrupted or the server went away. Re-prints this orientation.")
    print()
    print("  owrap stop")
    print("      Kill the opencode server and clear all session files.")
    print()
    print("  owrap cleanup")
    print("      Remove stale sessions (>2h or PPID-based). With ID arg: target by partial session_id or filename.")
    print()
    print("  owrap start <name>")
    print("      Start a new session for a different project.")
    print()
    print("  owrap finish <target>")
    print("      Kill a running job by target: 'exec', 'task', 'task1', 'task2', 'msg1', ...")
    print("      Sends SIGTERM to the job's PID. Use when a job hangs or you want to cancel it.")
    print()
    print("  owrap setup [path]")
    print("      Configure research_root, check template files.")
    _sys.stdout = _orig_out
    _out = _buf.getvalue()
    if not _in_path:
        for _cmd in ("oread", "orun", "oexec", "owrap", "owait"):
            _out = _re.sub(rf'\b{_cmd}\b', f'~/bin/{_cmd}', _out)
    _sys.stdout.write(_out)
