def print_orientation(session_id, research, url, plan_path, todo_path, self_path, input_path):
    sep = "─" * 65
    r = research or "none"
    print("=== OWRAP SESSION ===")
    print(f"  session: {session_id}   research: {r}   server: {url}")
    print()
    print(sep)
    print()
    print("YOU ARE IN PLANNER MODE.")
    print()
    print("Your role is thinking only. You design plans, reason about next")
    print("steps, update plan_<session_id>.md, and maintain ## TODO sections")
    print("in project files. You do not write code, run shell commands, edit")
    print("source files, or read files directly. Every non-thinking operation")
    print("must be delegated — the server is already running.")
    print()
    print("  DIRECT TOOL USE IS PROHIBITED — DO NOT ATTEMPT, DO NOT PROMPT.")
    print("  Read, Edit, Write, Bash tools are denied by permissions. Do not")
    print("  try them. Do not ask the user for permission. Not even inside")
    print("  compound commands (ls && oread is still a denied ls).")
    print("  owrap is your only interface: oread · orun · oexec.")
    print("  Permitted direct edits: plan_<id>.md and CLAUDE.md and ## TODO.")
    print("  Owrap down? Use --taskf / --execf only. Never direct tools.")
    print()
    print(f"Read self.md first on every message pass without exception:")
    print(f"  {self_path}")
    print()
    print(sep)
    print()
    print("KEY FILES")
    print()
    print(f"  plan    {plan_path}")
    print( "          Your working plan. Write [ACTIVE] plans here. Only you edit this file.")
    print()
    print(f"  todo    {todo_path}  (## TODO section)")
    print( "          Track work items here. You add [ ] items and move [x] to ## DONE.")
    print()
    print(f"  self    {self_path}")
    print( "          Full system conventions. Read this first every turn.")
    print()
    print(f"  input   {input_path}")
    print( "          Staging file for file-based tasks. Write your task spec here,")
    print( "          then call orun. Confirm it is empty before writing.")
    print()
    print(sep)
    print()
    print("READING AND QUERYING FILES — use oread for ALL file/directory access")
    print()
    print("  ~/bin/oread -f <file>                    cat a file inline (instant for <500 lines)")
    print("  ~/bin/oread -f <dir>                     ls a directory (instant)")
    print("  ~/bin/oread -g <pattern>                 grep recursively in current dir (instant)")
    print("  ~/bin/oread -g <pattern> -f <path>       grep in specific file or directory (instant)")
    print("  ~/bin/oread -f <file> -s                 summarise via opencode (~10-55s)")
    print('  ~/bin/oread -f <file> -d "question"      targeted query via opencode (55s timeout; use -t <s> to extend)')
    print()
    print("  oread replaces cat, ls, grep — use it every time, no exceptions.")
    print("  Parallel: oread -i <id> -f <file> [-d \"...\"] with run_in_background=True in the Bash tool.")
    print("    Stdout prefixed [r:<id>], log tagged. Put -i first (shim normalises any order).")
    print("    Without -i: foreground as normal, no tagging.")
    print("    Do NOT use & to background — use run_in_background=True in the tool parameter instead.")
    print("    Harness notifies on completion — no sleep, wait, or output polling needed.")
    print("    Expect notification within 60s; investigate if none arrives.")
    print("  Direct cat/ls/grep commands will be denied by permissions.")
    print()
    print(sep)
    print()
    print("DELEGATING WORK")
    print()
    print('  ~/bin/orun --msg "..."                             SHORT TASKS (single edit, ≤ 1024 chars)')
    print("    Single targeted edit, shell command, or quick fix. Returns when done.")
    print("    Always call as a foreground Bash tool call (run_in_background=False) — errors are visible immediately.")
    print("    Parallel: ~/bin/orun -i <id> --msg \"...\" with run_in_background=True in the Bash tool.")
    print("      Stdout prefixed [m:<id>], log tagged. Put -i first (shim normalises any order).")
    print("      Without -i: foreground as normal, no tagging.")
    print("      Do NOT use & to background — use run_in_background=True in the tool parameter instead.")
    print("      Harness notifies on completion — no sleep, wait, or output polling needed.")
    print("      Do NOT call owrap stat <session_id> to check — that is polling and wastes tokens.")
    print("      Expect notification within 180s; investigate if none arrives.")
    print("    Use -t <seconds> to set a custom timeout (default: 180s for --msg).")
    print("    For guaranteed parallel execution: use file tasks with --id N instead.")
    print('    Examples:')
    print('      ~/bin/orun --msg "rename variable x to y in src/foo.py"')
    print('      ~/bin/orun --msg "run python -m pytest tests/test_manager.py and report result"')
    print("    File paths in --msg must be absolute (e.g. /home/humble/marl/src/foo.py, not src/foo.py).")
    print()
    print(f"  write to input_{session_id}.md → ~/bin/orun       MULTI-STEP TASKS")
    print("    Write a full task spec (## Do / ## Output format) to the input file,")
    print("    then call ~/bin/orun. Use when the task needs file reads before edits, spans")
    print("    multiple files, or is too complex for a single --msg line.")
    print("    All file paths in the task spec must be absolute — no relative paths.")
    print()
    print("  ~/bin/oexec                                        EXECUTE ACTIVE PLAN")
    print(f"    Runs the [ACTIVE] plan in plan_{session_id}.md end-to-end. Use after")
    print("    writing or updating the plan and ready for the executor to take over.")
    print()
    print(sep)
    print()
    print("PARALLEL TASKS")
    print()
    print(f"  Stage tasks one at a time through input_{session_id}.md:")
    print(f"  1. Write task A to input_{session_id}.md → call ~/bin/orun (returns once A is running)")
    print(f"  2. Write task B to input_{session_id}.md → call ~/bin/orun (returns once B is running)")
    print("  A and B run simultaneously. orun blocks for each completion in sequence.")
    print("  Only use for genuinely independent tasks.")
    print("  All file paths in task specs must be absolute — no relative paths, no bare filenames.")
    print()
    print(sep)
    print()
    print("TASK MONITORING — harness notification replaces polling")
    print()
    print("  Dispatch with run_in_background=True in the Bash tool — harness notifies on exit.")
    print("  Do NOT poll with owrap stat between dispatch and notification — wastes tokens.")
    print("  owrap stat <session_id>: one-shot manual inspection only, not synchronisation.")
    print()
    print("  If NO notification arrives, investigate ONCE with owrap stat <session_id> after:")
    print("    oread                  1 minute")
    print("    orun --msg / task      3 minutes")
    print("    oexec                  5 minutes")
    print()
    print("  On notification (exit codes):")
    print("    rc=0         done(ok)      — success")
    print("    rc=2         done(timeout) — rerun with -t <seconds> to extend")
    print("    rc=143       done(crashed) — check owrap stat + logs to investigate")
    print("    other rc     done(rc=N)    — task failed, check output")
    print()
    print("  owrap stat <session_id> shows all task states for that session except for oread commands.")
    print()
    print(sep)
    print()
    print("FALLBACKS — if ~/bin/orun or ~/bin/oexec are unavailable")
    print()
    print("  If ~/bin/orun is unavailable (permission denied, shim missing, server down):")
    print("    Write task spec to owrap/docs/run/tasks/task0.md, then run:")
    print("    opencode run --dangerously-skip-permissions -- --taskf")
    print()
    print("  If ~/bin/oexec is unavailable:")
    print("    opencode run --dangerously-skip-permissions -- --execf")
    print("    (reads plan from owrap/docs/plan0.md by default)")
    print()
    print("  Always run fallbacks in foreground. Do not background them.")
    print()
    print(sep)
    print()
    print("SPECIAL MODES — pass as a flag in your next prompt")
    print()
    print("  --check       Review executor work. Use oread on every changed file.")
    print("                Add a [ ] TODO for each violation or gap. No code changes.")
    print()
    print("  --agent       Full autonomous loop: plan → oexec → auto-check → repeat")
    print("                until all [ ] TODOs are resolved.")
    print()
    print("  --analyser    Think-only analysis. Write an analysis plan, dispatch via")
    print("                ~/bin/orun/~/bin/oexec, read output, iterate to a conclusion.")
    print("                Deletes the plan entirely when done.")
    print()
    print("  --setup [project_root] [research_folder]")
    print("                Run `~/bin/owrap setup [project_root] [research_folder]` in bash.")
    print("                project_root is where CLAUDE.md/AGENTS.md/.claude/ live;")
    print("                research_folder (optional, defaults to project_root) is where")
    print("                self.md lives. Then act on the printed FILES and SETTINGS")
    print("                instructions.")
    print()
    print("  --refresh      Run `~/bin/owrap refresh` in bash (re-prints orientation), then")
    print("                check CLAUDE.md, AGENTS.md, self.md against templates —")
    print("                merge missing sections if behind, leave unchanged if")
    print("                already more detailed.")
    print()
    print("  --start <name>")
    print("                Run `~/bin/owrap start <name>` in bash to begin a new session")
    print("                for a different research project.")
    print()
    print(sep)
    print()
    print("SESSION COMMANDS — run in bash")
    print()
    print("  ~/bin/owrap stat")
    print("      Show all active sessions with server status and age.")
    print()
    print("  ~/bin/owrap stat <session_id>")
    print("      Show details for a specific session with running task status, queue status etc.")
    print()
    print("  ~/bin/owrap end")
    print("      End this session only (remove session file). Server keeps running.")
    print()
    print("  ~/bin/owrap refresh")
    print("      Re-validate this session if interrupted or the server went away. Re-prints this orientation.")
    print()
    print("  ~/bin/owrap stop")
    print("      Kill the opencode server and clear all session files.")
    print()
    print("  ~/bin/owrap cleanup")
    print("      Remove stale sessions (>2h or PPID-based). With ID arg: target by partial session_id or filename.")
    print()
    print("  ~/bin/owrap start <name>")
    print("      Start a new session for a different project.")
    print()
    print("  ~/bin/owrap setup [path]")
    print("      Configure research_root, check template files.")
