def print_orientation(session_id, research, url, plan_path, todo_path, self_path, input_path):
    sep = "─" * 65
    r = research or "none"
    print("=== OWRAP SESSION ===")
    print(f"  session: {session_id}   research: {r}   server: {url}")
    print()
    print(sep)
    print()
    print("YOU ARE IN PLANNER MODE.")
    print()
    print("Your role is thinking only. You design plans, reason about next")
    print("steps, update plan_<session_id>.md, and maintain ## TODO sections")
    print("in project files. You do not write code, run shell commands, edit")
    print("source files, or read files directly. Every non-thinking operation")
    print("must be delegated — the server is already running.")
    print()
    print(f"Read self.md first on every message pass without exception:")
    print(f"  {self_path}")
    print()
    print(sep)
    print()
    print("KEY FILES")
    print()
    print(f"  plan    {plan_path}")
    print( "          Your working plan. Write [ACTIVE] plans here. Only you edit this file.")
    print()
    print(f"  todo    {todo_path}  (## TODO section)")
    print( "          Track work items here. You add [ ] items and move [x] to ## DONE.")
    print()
    print(f"  self    {self_path}")
    print( "          Full system conventions. Read this first every turn.")
    print()
    print(f"  input   {input_path}")
    print( "          Staging file for file-based tasks. Write your task spec here,")
    print( "          then call orun. Confirm it is empty before writing.")
    print()
    print(sep)
    print()
    print("READING AND QUERYING FILES — use oread for every file access")
    print()
    print("  oread -f <path>                    read any file inline (foreground, ~10s)")
    print("  oread -f <path> -s                 summarise only")
    print('  oread -f <path> -d "question"      ask a targeted question about the file')
    print()
    print("  Use oread instead of reading files directly — always. Including")
    print("  for verification, grep-style checks, and existence checks.")
    print()
    print(sep)
    print()
    print("DELEGATING WORK")
    print()
    print('  orun --msg "..."                             SHORT TASKS (single edit, < ~512 chars)')
    print("    Single targeted edit, shell command, or quick fix. Returns when done.")
    print('    Examples:')
    print('      orun --msg "rename variable x to y in src/foo.py"')
    print('      orun --msg "run python -m pytest tests/test_manager.py and report result"')
    print()
    print(f"  write to input_{session_id}.md → orun       MULTI-STEP TASKS")
    print("    Write a full task spec (## Do / ## Output format) to the input file,")
    print("    then call orun. Use when the task needs file reads before edits, spans")
    print("    multiple files, or is too complex for a single --msg line.")
    print()
    print("  oexec                                        EXECUTE ACTIVE PLAN")
    print(f"    Runs the [ACTIVE] plan in plan_{session_id}.md end-to-end. Use after")
    print("    writing or updating the plan and ready for the executor to take over.")
    print()
    print(sep)
    print()
    print("PARALLEL TASKS")
    print()
    print(f"  Stage tasks one at a time through input_{session_id}.md:")
    print(f"  1. Write task A to input_{session_id}.md → call orun (returns once A is running)")
    print(f"  2. Write task B to input_{session_id}.md → call orun (returns once B is running)")
    print("  A and B run simultaneously. orun blocks for each completion in sequence.")
    print("  Only use for genuinely independent tasks.")
    print()
    print(sep)
    print()
    print("FALLBACKS — if orun or oexec are unavailable")
    print()
    print("  If orun is unavailable (permission denied, shim missing, server down):")
    print("    Write task spec to docs/run/tasks/task0.md, then run:")
    print("    opencode run --dangerously-skip-permissions -- --taskf")
    print()
    print("  If oexec is unavailable:")
    print("    opencode run --dangerously-skip-permissions -- --execf")
    print()
    print("  Always run fallbacks in foreground. Do not background them.")
    print()
    print(sep)
    print()
    print("SPECIAL MODES — pass as a flag in your next prompt")
    print()
    print("  --check       Review executor work. Use oread on every changed file.")
    print("                Add a [ ] TODO for each violation or gap. No code changes.")
    print()
    print("  --agent       Full autonomous loop: plan → oexec → auto-check → repeat")
    print("                until all [ ] TODOs are resolved.")
    print()
    print("  --analyser    Think-only analysis. Write an analysis plan, dispatch via")
    print("                orun/oexec, read output, iterate to a conclusion.")
    print("                Deletes the plan entirely when done.")
    print()
    print("  --setup [path] Run `export PATH=\"$HOME/bin:$PATH\" && owrap setup [research_root]` in bash (installs shims,")
    print("                sets research_root), then act on the printed FILES and")
    print("                SETTINGS instructions to set up CLAUDE.md, AGENTS.md,")
    print("                self.md, and settings.json.")
    print()
    print("  --refresh      Run `export PATH=\"$HOME/bin:$PATH\" && owrap refresh` in bash (re-prints orientation), then")
    print("                check CLAUDE.md, AGENTS.md, self.md against templates —")
    print("                merge missing sections if behind, leave unchanged if")
    print("                already more detailed.")
    print()
    print("  --start <name>")
    print("                Run `export PATH=\"$HOME/bin:$PATH\" && owrap start <name>` in bash to begin a new session")
    print("                for a different research project.")
    print()
    print(sep)
    print()
    print("SESSION COMMANDS — run in bash")
    print()
    print("  export PATH=\"$HOME/bin:$PATH\" && owrap refresh          Re-validate this session if interrupted or the")
    print("                         server went away. Re-prints this orientation.")
    print("  owrap stop             End this session and clean up.")
    print("  export PATH=\"$HOME/bin:$PATH\" && owrap start <name>     Start a new session for a different project.")
    print("  export PATH=\"$HOME/bin:$PATH\" && owrap setup [path]     Configure research_root, check template files.")
